messages:
  broadcastPrefix: "&c[Broadcast] "
  noPermissions: "&cYou do not have permission to use this command"
  invalidInteger: "&cYou must use a positive integer"
  generalError: "&cAn error occured while performing the command"
  noType: "&cPlease provide a valid type to broadcast (chat, gui or all)"
  noMessage: "&cPlease provide a valid message to broadcast"
  wrongUsage: "&cIncorrect usage of this command.\nUsage:&f%usage%"