name: Broadcast
version: 1.1.3
main: com.lightninq720.Broadcast
description: Broadcast plugin

commands:
  broadcast:
    description: Send a broadcasted message to all server players
    usage: /broadcast <type> <message>
  countdown:
    description: Start a countdown to send to all server players
    usage: /countdown <type> <seconds>