name: Broadcast
version: 1.0.0
main: com.lightninq720.Broadcast
description: Broadcast plugin

commands:
  broadcast:
    description: Send a broadcasted message to all server players
    usage: /broadcast <message>
  countdown:
    description: Start a countdown to send to all server players
    usage: /countdown <seconds>